<!-- DESENVOLVIDO POR DINHO NUNES LC | dinhonuneslc@gmail.com / +55 (99) 9 8439-1782 -->

<?php

# PERSONALIZAÇÃO

$loja= "CENTRAL DE DOWNLOAD"; //Smartplay Downloads

$serv= "SERVIDOR"; //NOME DO SERVIDOR

$favi= "favicon.ico"; //TEXTO DE DIREITOS AUTORAIS

$logo= "logo.jpg"; //LOGO DA LOJA OU SERVIDOR

$banner= "banner.jpg"; //FUNDO DA LOJA OU SERVIDOR

$copy= "TODOS OS DIREITOS RESERVADOS"; //TEXTO DE DIREITOS AUTORAIS

$CREDITOS= "DESENVOLVIDO POR DINHO NUNES LC | dinhonuneslc@gmail.com / +55 (99) 9 8439-1782"; //NÃO REMOVA OU MODIFIQUE OS CRÉDITOS

# APLICATIVOS

//APLICATIVO 01

$app1= "ATIVO"; // DEIXE "ATIVO" PARA EXIBIR A CAIXA REFERENTE AO APLICATIVO NA PÁGINA DE DOWNLOADS, REMOVA PARA OCULTAR.

$appnome1= "APLICATIVO 01"; //NOME DO APLICATIVO 01

$applink1= ""; //LINK DO APLICATIVO 01

$appimg1= "01.jpeg"; //IMAGEM DO APLICATIVO 01

//APLICATIVO 02

$app2= "ATIVO"; // DEIXE "ATIVO" PARA EXIBIR A CAIXA REFERENTE AO APLICATIVO NA PÁGINA DE DOWNLOADS, REMOVA PARA OCULTAR.

$appnome2= "APLICATIVO 02"; //NOME DO APLICATIVO 02

$applink2= ""; //LINK DO APLICATIVO 02

$appimg2= "02.jpeg"; //IMAGEM DO APLICATIVO 02

//APLICATIVO 03

$app3= "ATIVO"; // DEIXE "ATIVO" PARA EXIBIR A CAIXA REFERENTE AO APLICATIVO NA PÁGINA DE DOWNLOADS, REMOVA PARA OCULTAR.

$appnome3= "APLICATIVO 03"; //NOME DO APLICATIVO 03

$applink3= ""; //LINK DO APLICATIVO 03

$appimg3= "03.jpeg"; //IMAGEM DO APLICATIVO 03

//APLICATIVO 04

$app4= "ATIVO"; // DEIXE "ATIVO" PARA EXIBIR A CAIXA REFERENTE AO APLICATIVO NA PÁGINA DE DOWNLOADS, REMOVA PARA OCULTAR.

$appnome4= "APLICATIVO 04"; //NOME DO APLICATIVO 04

$applink4= ""; //LINK DO APLICATIVO 04

$appimg4= "04.jpeg"; //IMAGEM DO APLICATIVO 04

//APLICATIVO 05

$app5= "ATIVO"; // DEIXE "ATIVO" PARA EXIBIR A CAIXA REFERENTE AO APLICATIVO NA PÁGINA DE DOWNLOADS, REMOVA PARA OCULTAR.

$appnome5= "APLICATIVO 05"; //NOME DO APLICATIVO 05

$applink5= ""; //LINK DO APLICATIVO 05

$appimg5= "05.jpeg"; //IMAGEM DO APLICATIVO 05

//APLICATIVO 06

$app6= "ATIVO"; // DEIXE "ATIVO" PARA EXIBIR A CAIXA REFERENTE AO APLICATIVO NA PÁGINA DE DOWNLOADS, REMOVA PARA OCULTAR.

$appnome6= "APLICATIVO 06"; //NOME DO APLICATIVO 05

$applink6= ""; //LINK DO APLICATIVO 05

$appimg6= "06.jpeg"; //IMAGEM DO APLICATIVO 05

?>
